import test from 'node:test'
import assert from 'node:assert/strict'
import { spawn } from 'node:child_process'
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'

function runProcess(args, options = {}) {
  const cwd = options.cwd || process.cwd()
  return new Promise((resolveRun) => {
    const child = spawn(process.execPath, args, {
      cwd,
      env: { ...process.env },
      stdio: ['ignore', 'pipe', 'pipe'],
    })

    let stdout = ''
    let stderr = ''
    child.stdout.on('data', (chunk) => {
      stdout += String(chunk)
    })
    child.stderr.on('data', (chunk) => {
      stderr += String(chunk)
    })

    child.once('exit', (code, signal) => {
      resolveRun({ code, signal, stdout, stderr })
    })
  })
}

test('nerve-compose exits with argument error when subcommand is missing', async () => {
  const result = await runProcess(['bin/nerve-compose.js'])
  assert.equal(result.code, 2)
  assert.equal(result.stderr.includes('nerve-compose argument error'), true)
})

test('nerve-compose init scaffolds nerve.json and workflow in cwd by default', async () => {
  const workspaceRoot = await mkdtemp(path.join(os.tmpdir(), 'nerve-compose-init-'))

  try {
    const result = await runProcess([
      path.join(process.cwd(), 'bin', 'nerve-compose.js'),
      'init',
      '--json',
    ], { cwd: workspaceRoot })
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.command, 'init')

    const nervePath = path.join(workspaceRoot, 'nerve.json')
    const workflowPath = path.join(workspaceRoot, 'workflow.nrv')
    const nerveRaw = await readFile(nervePath, 'utf8')
    const nerve = JSON.parse(nerveRaw)
    assert.equal(nerve.entrypointPath, 'workflow.nrv')
    assert.equal(nerve.baselineStatePath, 'state.init.json')
    assert.deepEqual(nerve.externals, ['user_message'])

    const baselineStateRaw = await readFile(path.join(workspaceRoot, 'state.init.json'), 'utf8')
    const baselineState = JSON.parse(baselineStateRaw)
    assert.deepEqual(baselineState, { count: 0 })

    const workflowRaw = await readFile(workflowPath, 'utf8')
    assert.equal(workflowRaw.includes('Generated by nerve-compose init'), true)
    assert.equal(workflowRaw.includes('on external "user_message"'), true)
    assert.equal(workflowRaw.includes('(no output, ${state.count})'), true)
    assert.equal(workflowRaw.includes('hello world!'), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose init in explicit workspaceDir creates files in target path', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-init-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'init', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.command, 'init')

    const nerveRaw = await readFile(path.join(workspaceRoot, 'nerve.json'), 'utf8')
    const nerve = JSON.parse(nerveRaw)
    assert.equal(nerve.entrypointPath, 'workflow.nrv')
    assert.equal(nerve.baselineStatePath, 'state.init.json')

    const baselineStateRaw = await readFile(path.join(workspaceRoot, 'state.init.json'), 'utf8')
    const baselineState = JSON.parse(baselineStateRaw)
    assert.deepEqual(baselineState, { count: 0 })

    const workflowRaw = await readFile(path.join(workspaceRoot, 'workflow.nrv'), 'utf8')
    assert.equal(workflowRaw.includes('hello world!'), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose init is non-destructive when nextv.json exists without nerve.json', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-init-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'init', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    const nerveEntry = payload.files.find((entry) => String(entry.path || '').endsWith('nerve.json'))
    assert.equal(Boolean(nerveEntry), true)
    assert.equal(nerveEntry.action, 'skipped')

    const createdNerve = await readFile(path.join(workspaceRoot, 'nerve.json'), 'utf8').catch(() => null)
    const createdWorkflow = await readFile(path.join(workspaceRoot, 'workflow.nrv'), 'utf8').catch(() => null)
    assert.equal(createdNerve, null)
    assert.equal(createdWorkflow, null)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose init does not overwrite existing workflow when nerve.json exists', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-init-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')
  const existingWorkflow = 'workflow custom {\n  on user_message { output text "keep" }\n}\n'

  await writeFile(path.join(workspaceRoot, 'nerve.json'), JSON.stringify({ entrypointPath: 'workflow.nrv' }, null, 2), 'utf8')
  await writeFile(path.join(workspaceRoot, 'workflow.nrv'), existingWorkflow, 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'init', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const workflowRaw = await readFile(path.join(workspaceRoot, 'workflow.nrv'), 'utf8')
    assert.equal(workflowRaw, existingWorkflow)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose modules --json returns composition payload', async () => {
  const result = await runProcess(['bin/nerve-compose.js', 'modules', '--json'])
  assert.equal(result.code, 0)

  const payload = JSON.parse(result.stdout)
  assert.equal(payload.ok, true)
  assert.equal(payload.command, 'modules')
  assert.equal(typeof payload.workspaceDir, 'string')
  assert.equal(typeof payload.builtinOnly, 'boolean')
  assert.equal(typeof payload.totals?.toolProviders, 'number')
  assert.equal(Array.isArray(payload.sources), true)

  const builtin = payload.sources.find((source) => source?.name === 'builtin')
  assert.equal(Boolean(builtin), true)
  assert.equal(typeof builtin.counts?.toolProviders, 'number')
})

test('nerve-compose modules --builtin-only excludes non-builtin sources', async () => {
  const result = await runProcess(['bin/nerve-compose.js', 'modules', '--builtin-only', '--json'])
  assert.equal(result.code, 0)

  const payload = JSON.parse(result.stdout)
  assert.equal(payload.builtinOnly, true)
  assert.equal(Array.isArray(payload.sources), true)
  assert.equal(payload.sources.length, 1)
  assert.equal(payload.sources[0].name, 'builtin')
})

test('nerve-compose doctor --json returns health report for example workspace', async () => {
  const result = await runProcess(['bin/nerve-compose.js', 'doctor', 'examples/mqtt-simple-host', '--json'])
  assert.equal(result.code, 0)

  const payload = JSON.parse(result.stdout)
  assert.equal(payload.ok, true)
  assert.equal(payload.command, 'doctor')
  assert.equal(typeof payload.effectsPolicy, 'string')
  assert.equal(typeof payload.summary?.errors, 'number')
  assert.equal(Array.isArray(payload.issues), true)
  assert.equal(typeof payload.config?.nextv, 'string')
})

test('nerve-compose doctor fails strict capability checks for missing bindings', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-doctor-'))
  const nextvPath = path.join(workspaceRoot, 'nextv.json')
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(nextvPath, JSON.stringify({
    effectsPolicy: 'strict',
    requires: {
      memory: {
        required: true,
      },
    },
    modules: {},
  }, null, 2), 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'doctor', workspaceRelativePath, '--json'])
    assert.equal(result.code, 1)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, false)
    assert.equal(payload.effectsPolicy, 'strict')
    const hasMissingBinding = payload.issues.some((issue) => String(issue.code) === 'MISSING_BINDING')
    assert.equal(hasMissingBinding, true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add memory-pgvector scaffolds workspace files', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-add-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({
    entrypointPath: 'entry.nrv',
    externals: ['user_message'],
  }, null, 2), 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'memory-pgvector', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.command, 'add')
    assert.equal(payload.capability, 'memory-pgvector')
    assert.equal(Array.isArray(payload.files), true)

    const hostModulesSource = await readFile(path.join(workspaceRoot, 'host_modules', 'index.js'), 'utf8')
    const expectedImportPathRaw = path.relative(
      path.join(workspaceRoot, 'host_modules'),
      path.join(process.cwd(), 'src', 'host_modules', 'public', 'index.js'),
    ).replace(/\\/g, '/')
    const expectedImportPath = expectedImportPathRaw.startsWith('.')
      ? expectedImportPathRaw
      : `./${expectedImportPathRaw}`
    assert.equal(hostModulesSource.includes('Generated by nerve-compose add memory-pgvector'), true)
    assert.equal(hostModulesSource.includes('createMemoryProvider'), true)
    assert.equal(hostModulesSource.includes(`from '${expectedImportPath}'`), true)

    const envExample = await readFile(path.join(workspaceRoot, '.env.example'), 'utf8')
    assert.equal(envExample.includes('MEMORY_DB_URL='), true)
    assert.equal(envExample.includes('MEMORY_EMBEDDING_MODEL='), true)

    const nextvRaw = await readFile(path.join(workspaceRoot, 'nextv.json'), 'utf8')
    const nextv = JSON.parse(nextvRaw)
    assert.deepEqual(nextv.requires?.memory, { required: true, provider: 'memory' })
    assert.deepEqual(nextv.modules?.memory, { provider: 'memory-pgvector', mode: 'embedded' })
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add memory-pgvector updates nerve.json when both config files exist', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-add-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nerve.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')
  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'memory-pgvector', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    const configEntry = payload.files.find((entry) => String(entry.path || '').endsWith('nerve.json'))
    assert.equal(Boolean(configEntry), true)

    const nerveRaw = await readFile(path.join(workspaceRoot, 'nerve.json'), 'utf8')
    const nerve = JSON.parse(nerveRaw)
    assert.deepEqual(nerve.requires?.memory, { required: true, provider: 'memory' })
    assert.deepEqual(nerve.modules?.memory, { provider: 'memory-pgvector', mode: 'embedded' })

    const nextvRaw = await readFile(path.join(workspaceRoot, 'nextv.json'), 'utf8')
    const nextv = JSON.parse(nextvRaw)
    assert.equal(nextv.requires?.memory, undefined)
    assert.equal(nextv.modules?.memory, undefined)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add transport ollama registers transport and env placeholders', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-transport-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nerve.json'), JSON.stringify({ entrypointPath: 'workflow.nrv' }, null, 2), 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'transport', 'ollama', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.capability, 'transport:ollama')

    const nerve = JSON.parse(await readFile(path.join(workspaceRoot, 'nerve.json'), 'utf8'))
    assert.deepEqual(nerve.transports?.ollama, {
      provider: 'ollama',
      baseUrl: '${env:OLLAMA_BASE_URL}',
    })

    const envExample = await readFile(path.join(workspaceRoot, '.env.example'), 'utf8')
    assert.equal(envExample.includes('OLLAMA_BASE_URL='), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add transport is idempotent on rerun', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-transport-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nerve.json'), JSON.stringify({ entrypointPath: 'workflow.nrv' }, null, 2), 'utf8')

  try {
    const first = await runProcess(['bin/nerve-compose.js', 'add', 'transport', 'ollama', workspaceRelativePath, '--json'])
    assert.equal(first.code, 0)

    const second = await runProcess(['bin/nerve-compose.js', 'add', 'transport', 'ollama', workspaceRelativePath, '--json'])
    assert.equal(second.code, 0)

    const payload = JSON.parse(second.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.files.every((entry) => entry.action === 'unchanged' || entry.action === 'updated' || entry.action === 'skipped'), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add model registers model with existing transport', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-model-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nerve.json'), JSON.stringify({
    entrypointPath: 'workflow.nrv',
    transports: {
      ollama: {
        provider: 'ollama',
      },
    },
  }, null, 2), 'utf8')

  try {
    const result = await runProcess([
      'bin/nerve-compose.js',
      'add',
      'model',
      'llama3.2',
      '--transport',
      'ollama',
      workspaceRelativePath,
      '--json',
    ])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.capability, 'model:llama3.2')

    const nerve = JSON.parse(await readFile(path.join(workspaceRoot, 'nerve.json'), 'utf8'))
    assert.deepEqual(nerve.models?.['llama3.2'], {
      model: 'llama3.2',
      transport: 'ollama',
    })
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add model fails when referenced transport is missing', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-model-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nerve.json'), JSON.stringify({ entrypointPath: 'workflow.nrv' }, null, 2), 'utf8')

  try {
    const result = await runProcess([
      'bin/nerve-compose.js',
      'add',
      'model',
      'llama3.2',
      '--transport',
      'ollama',
      workspaceRelativePath,
      '--json',
    ])
    assert.equal(result.code, 1)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, false)
    const skipped = payload.files.find((entry) => String(entry.message || '').includes('transport "ollama" not found'))
    assert.equal(Boolean(skipped), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add model requires --transport flag', async () => {
  const result = await runProcess(['bin/nerve-compose.js', 'add', 'model', 'llama3.2', '--json'])
  assert.equal(result.code, 2)
  assert.equal(result.stderr.includes('add model requires --transport <transportName>'), true)
})

test('nerve-compose add memory-pgvector is idempotent on rerun', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-add-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')

  try {
    const first = await runProcess(['bin/nerve-compose.js', 'add', 'memory-pgvector', workspaceRelativePath, '--json'])
    assert.equal(first.code, 0)

    const second = await runProcess(['bin/nerve-compose.js', 'add', 'memory-pgvector', workspaceRelativePath, '--json'])
    assert.equal(second.code, 0)

    const payload = JSON.parse(second.stdout)
    const actions = payload.files.map((entry) => entry.action)
    assert.equal(actions.every((action) => action === 'unchanged' || action === 'updated' || action === 'skipped'), true)

    const envExample = await readFile(path.join(workspaceRoot, '.env.example'), 'utf8')
    const dbUrlMatches = envExample.match(/MEMORY_DB_URL=/g) || []
    assert.equal(dbUrlMatches.length, 1)

    const hostModulesSource = await readFile(path.join(workspaceRoot, 'host_modules', 'index.js'), 'utf8')
    const createMemoryProviderMatches = hostModulesSource.match(/createMemoryProvider/g) || []
    assert.equal(createMemoryProviderMatches.length, 2)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add memory-pgvector becomes visible in modules after env is provided', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), 'workspaces-local', '.tmp-compose-add-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')

  try {
    const addResult = await runProcess(['bin/nerve-compose.js', 'add', 'memory-pgvector', workspaceRelativePath, '--json'])
    assert.equal(addResult.code, 0)

    await writeFile(path.join(workspaceRoot, '.env'), 'MEMORY_DB_URL=postgres://example/test\n', 'utf8')

    const modulesResult = await runProcess(['bin/nerve-compose.js', 'modules', workspaceRelativePath, '--json'])
    assert.equal(modulesResult.code, 0)

    const payload = JSON.parse(modulesResult.stdout)
    const workspaceSource = payload.sources.find((source) => source?.name === 'workspace')
    assert.equal(Boolean(workspaceSource), true)
    assert.equal(Number(workspaceSource.counts?.toolProviders) > 0, true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add speech scaffolds env, nextv config, and speech surface', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-speech-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'speech', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.capability, 'speech')
    assert.equal(Array.isArray(payload.files), true)

    const hostModulesSource = await readFile(path.join(workspaceRoot, 'host_modules', 'index.js'), 'utf8')
    assert.equal(hostModulesSource.includes('Generated by nerve-compose add speech'), true)
    assert.equal(hostModulesSource.includes('createWhisperIngressConnector'), true)
    assert.equal(hostModulesSource.includes('createPiperEffectRealizer'), true)

    const envExample = await readFile(path.join(workspaceRoot, '.env.example'), 'utf8')
    assert.equal(envExample.includes('WHISPER_RUN_PATH='), true)
    assert.equal(envExample.includes('PIPER_RUN_PATH='), true)
    assert.equal(envExample.includes('VOICE_TRANSPORT_MODE='), true)

    const nextvRaw = await readFile(path.join(workspaceRoot, 'nextv.json'), 'utf8')
    const nextv = JSON.parse(nextvRaw)
    assert.deepEqual(nextv.requires?.speech, { required: true, provider: 'speech' })
    assert.deepEqual(nextv.modules?.speech, { provider: 'speech-surface', mode: 'embedded' })

    const speechSurfaceServer = await readFile(path.join(workspaceRoot, 'speech-surface', 'server.js'), 'utf8')
    assert.equal(speechSurfaceServer.includes('/api/voice-command'), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add speech is idempotent on rerun', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-speech-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')

  try {
    const first = await runProcess(['bin/nerve-compose.js', 'add', 'speech', workspaceRelativePath, '--json'])
    assert.equal(first.code, 0)

    const second = await runProcess(['bin/nerve-compose.js', 'add', 'speech', workspaceRelativePath, '--json'])
    assert.equal(second.code, 0)

    const payload = JSON.parse(second.stdout)
    const actions = payload.files.map((entry) => entry.action)
    assert.equal(actions.includes('created'), false)
    assert.equal(actions.every((action) => action === 'unchanged' || action === 'updated' || action === 'skipped'), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})
