import test from 'node:test'
import assert from 'node:assert/strict'
import { spawn } from 'node:child_process'
import { createServer } from 'node:http'
import { existsSync } from 'node:fs'
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'

function runProcess(args, options = {}) {
  const cwd = options.cwd || process.cwd()
  return new Promise((resolveRun) => {
    const child = spawn(process.execPath, args, {
      cwd,
      env: { ...process.env },
      stdio: ['ignore', 'pipe', 'pipe'],
    })

    let stdout = ''
    let stderr = ''
    child.stdout.on('data', (chunk) => {
      stdout += String(chunk)
    })
    child.stderr.on('data', (chunk) => {
      stderr += String(chunk)
    })

    child.once('exit', (code, signal) => {
      resolveRun({ code, signal, stdout, stderr })
    })
  })
}

async function startMockOllamaTagsServer(models) {
  const server = createServer((req, res) => {
    if (req.url === '/api/tags') {
      res.writeHead(200, { 'Content-Type': 'application/json; charset=utf-8' })
      res.end(JSON.stringify({ models: models.map((name) => ({ name })) }))
      return
    }

    res.writeHead(404, { 'Content-Type': 'application/json; charset=utf-8' })
    res.end(JSON.stringify({ ok: false }))
  })

  await new Promise((resolveListen) => {
    server.listen(0, '127.0.0.1', resolveListen)
  })

  const address = server.address()
  const port = typeof address === 'object' && address ? address.port : 0
  return {
    baseUrl: `http://127.0.0.1:${port}`,
    close: () => new Promise((resolveClose) => server.close(resolveClose)),
  }
}

test('nerve-compose exits with argument error when subcommand is missing', async () => {
  const result = await runProcess(['bin/nerve-compose.js'])
  assert.equal(result.code, 2)
  assert.equal(result.stderr.includes('nerve-compose argument error'), true)
})

test('nerve-compose init scaffolds nerve.json and workflow in cwd by default', async () => {
  const workspaceRoot = await mkdtemp(path.join(os.tmpdir(), 'nerve-compose-init-'))

  try {
    const result = await runProcess([
      path.join(process.cwd(), 'bin', 'nerve-compose.js'),
      'init',
      '--json',
    ], { cwd: workspaceRoot })
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.command, 'init')

    const nervePath = path.join(workspaceRoot, 'nerve.json')
    const workflowPath = path.join(workspaceRoot, 'workflow.nrv')
    const nerveRaw = await readFile(nervePath, 'utf8')
    const nerve = JSON.parse(nerveRaw)
    assert.equal(nerve.entrypointPath, 'workflow.nrv')
    assert.equal(nerve.baselineStatePath, 'state.init.json')
    assert.deepEqual(nerve.externals, ['user_message'])

    const baselineStateRaw = await readFile(path.join(workspaceRoot, 'state.init.json'), 'utf8')
    const baselineState = JSON.parse(baselineStateRaw)
    assert.deepEqual(baselineState, { count: 0 })

    const workflowRaw = await readFile(workflowPath, 'utf8')
    assert.equal(workflowRaw.includes('Generated by nerve-compose init'), true)
    assert.equal(workflowRaw.includes('on external "user_message"'), true)
    assert.equal(workflowRaw.includes('(no output yet)'), true)
    assert.equal(workflowRaw.includes('hello world!'), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose init in explicit workspaceDir creates files in target path', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-init-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'init', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.command, 'init')

    const nerveRaw = await readFile(path.join(workspaceRoot, 'nerve.json'), 'utf8')
    const nerve = JSON.parse(nerveRaw)
    assert.equal(nerve.entrypointPath, 'workflow.nrv')
    assert.equal(nerve.baselineStatePath, 'state.init.json')

    const baselineStateRaw = await readFile(path.join(workspaceRoot, 'state.init.json'), 'utf8')
    const baselineState = JSON.parse(baselineStateRaw)
    assert.deepEqual(baselineState, { count: 0 })

    const workflowRaw = await readFile(path.join(workspaceRoot, 'workflow.nrv'), 'utf8')
    assert.equal(workflowRaw.includes('hello world!'), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose init is non-destructive when nextv.json exists without nerve.json', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-init-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'init', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    const nerveEntry = payload.files.find((entry) => String(entry.path || '').endsWith('nerve.json'))
    assert.equal(Boolean(nerveEntry), true)
    assert.equal(nerveEntry.action, 'skipped')

    const createdNerve = await readFile(path.join(workspaceRoot, 'nerve.json'), 'utf8').catch(() => null)
    const createdWorkflow = await readFile(path.join(workspaceRoot, 'workflow.nrv'), 'utf8').catch(() => null)
    assert.equal(createdNerve, null)
    assert.equal(createdWorkflow, null)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose init does not overwrite existing workflow when nerve.json exists', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-init-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')
  const existingWorkflow = 'workflow custom {\n  on user_message { output text "keep" }\n}\n'

  await writeFile(path.join(workspaceRoot, 'nerve.json'), JSON.stringify({ entrypointPath: 'workflow.nrv' }, null, 2), 'utf8')
  await writeFile(path.join(workspaceRoot, 'workflow.nrv'), existingWorkflow, 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'init', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const workflowRaw = await readFile(path.join(workspaceRoot, 'workflow.nrv'), 'utf8')
    assert.equal(workflowRaw, existingWorkflow)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose modules --json returns composition payload', async () => {
  const result = await runProcess(['bin/nerve-compose.js', 'modules', '--json'])
  assert.equal(result.code, 0)

  const payload = JSON.parse(result.stdout)
  assert.equal(payload.ok, true)
  assert.equal(payload.command, 'modules')
  assert.equal(typeof payload.workspaceDir, 'string')
  assert.equal(typeof payload.builtinOnly, 'boolean')
  assert.equal(typeof payload.totals?.toolProviders, 'number')
  assert.equal(Array.isArray(payload.sources), true)

  const builtin = payload.sources.find((source) => source?.name === 'builtin')
  assert.equal(Boolean(builtin), true)
  assert.equal(typeof builtin.counts?.toolProviders, 'number')
})

test('nerve-compose modules --builtin-only excludes non-builtin sources', async () => {
  const result = await runProcess(['bin/nerve-compose.js', 'modules', '--builtin-only', '--json'])
  assert.equal(result.code, 0)

  const payload = JSON.parse(result.stdout)
  assert.equal(payload.builtinOnly, true)
  assert.equal(Array.isArray(payload.sources), true)
  assert.equal(payload.sources.length, 1)
  assert.equal(payload.sources[0].name, 'builtin')
})

test('nerve-compose doctor --json returns health report for example workspace', async () => {
  const result = await runProcess(['bin/nerve-compose.js', 'doctor', 'examples/mqtt-simple-host', '--json'])
  assert.equal(result.code, 0)

  const payload = JSON.parse(result.stdout)
  assert.equal(payload.ok, true)
  assert.equal(payload.command, 'doctor')
  assert.equal(typeof payload.effectsPolicy, 'string')
  assert.equal(typeof payload.summary?.errors, 'number')
  assert.equal(Array.isArray(payload.issues), true)
  assert.equal(typeof payload.config?.nextv, 'string')
})

test('nerve-compose validate --json succeeds for workspace without required capabilities', async () => {
  const result = await runProcess(['bin/nerve-compose.js', 'validate', 'examples/mqtt-simple-host', '--json'])
  assert.equal(result.code, 0)

  const payload = JSON.parse(result.stdout)
  assert.equal(payload.ok, true)
  assert.equal(payload.command, 'validate')
  assert.equal(typeof payload.summary?.capabilities, 'number')
})

test('nerve-compose validate fails when required module provider is unsupported', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-validate-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({
    entrypointPath: 'entry.nrv',
    requires: {
      memory: {
        required: true,
        provider: 'memory',
      },
    },
    modules: {
      memory: {
        provider: 'unknown-provider',
        mode: 'embedded',
      },
    },
  }, null, 2), 'utf8')

  await writeFile(path.join(workspaceRoot, 'entry.nrv'), 'on external "user_message"\n  output text "ok"\nend\n', 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'validate', workspaceRelativePath, '--json'])
    assert.equal(result.code, 1)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, false)
    assert.equal(payload.command, 'validate')
    assert.equal(String(payload.error || '').includes('Unsupported workspace module provider'), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose validate reports resolved workspace capability bindings', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-validate-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({
    entrypointPath: 'entry.nrv',
    requires: {
      speech: {
        required: true,
        provider: 'speech',
      },
    },
    modules: {
      speech: {
        provider: 'speech-surface',
        mode: 'embedded',
      },
    },
  }, null, 2), 'utf8')

  await writeFile(path.join(workspaceRoot, 'entry.nrv'), 'on external "user_message"\n  output text "ok"\nend\n', 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'validate', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(Array.isArray(payload.resolvedCapabilities), true)
    assert.equal(payload.resolvedCapabilities.length, 1)
    assert.deepEqual(payload.resolvedCapabilities[0], {
      capabilityName: 'speech',
      moduleName: 'speech',
      provider: 'speech-surface',
      mode: 'embedded',
    })
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose validate accepts absolute workspace paths from a different cwd', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-validate-'))
  const parentCwd = path.dirname(process.cwd())

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')
  await writeFile(path.join(workspaceRoot, 'entry.nrv'), 'on external "user_message"\n  output text "ok"\nend\n', 'utf8')

  try {
    const result = await runProcess([path.join(process.cwd(), 'bin', 'nerve-compose.js'), 'validate', workspaceRoot, '--json'], { cwd: parentCwd })
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.command, 'validate')
    assert.equal(Array.isArray(payload.resolvedCapabilities), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose doctor fails strict capability checks for missing bindings', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-doctor-'))
  const nextvPath = path.join(workspaceRoot, 'nextv.json')
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(nextvPath, JSON.stringify({
    effectsPolicy: 'strict',
    requires: {
      memory: {
        required: true,
      },
    },
    modules: {},
  }, null, 2), 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'doctor', workspaceRelativePath, '--json'])
    assert.equal(result.code, 1)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, false)
    assert.equal(payload.effectsPolicy, 'strict')
    const hasMissingBinding = payload.issues.some((issue) => String(issue.code) === 'MISSING_BINDING')
    assert.equal(hasMissingBinding, true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add host composable scaffolds local host files', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-host-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'host', 'composable', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.command, 'add')
    assert.equal(payload.capability, 'host:composable')

    const serverPath = path.join(workspaceRoot, 'host', 'server.mjs')
    const readmePath = path.join(workspaceRoot, 'host', 'README.md')
    assert.equal(existsSync(serverPath), true)
    assert.equal(existsSync(readmePath), true)

    const serverSource = await readFile(serverPath, 'utf8')
    assert.equal(serverSource.includes('Generated by nerve-compose add host composable'), true)
    assert.equal(serverSource.includes('../node_modules/nerveflow/src/host_core/index.js'), true)

    const readmeSource = await readFile(readmePath, 'utf8')
    assert.equal(readmeSource.includes('Reference hosts provide learnable starting points.'), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add host defaults to composable profile when omitted', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-host-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'host', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.capability, 'host:composable')
    assert.equal(existsSync(path.join(workspaceRoot, 'host', 'server.mjs')), true)

    const hostServer = await readFile(path.join(workspaceRoot, 'host', 'server.mjs'), 'utf8')
    assert.equal(hostServer.includes("value.startsWith('\"') && value.endsWith('\"')"), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add host rejects unsupported profile', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-host-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'host', 'minimal', workspaceRelativePath, '--json'])
    assert.equal(result.code, 2)
    assert.equal(result.stderr.includes('Unsupported host profile: minimal'), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add host returns manual merge warning for user-managed host files', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-host-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await mkdir(path.join(workspaceRoot, 'host'), { recursive: true })
  await writeFile(path.join(workspaceRoot, 'host', 'server.mjs'), 'console.log("custom host")\n', 'utf8')
  await writeFile(path.join(workspaceRoot, 'host', 'README.md'), '# custom host\n', 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'host', 'composable', workspaceRelativePath, '--json'])
    assert.equal(result.code, 1)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, false)
    const blockedServer = payload.files.find((entry) => String(entry.path || '').replace(/\\/g, '/').endsWith('host/server.mjs'))
    assert.equal(Boolean(blockedServer), true)
    assert.equal(blockedServer.action, 'skipped_manual_merge')

    const preservedServer = await readFile(path.join(workspaceRoot, 'host', 'server.mjs'), 'utf8')
    assert.equal(preservedServer, 'console.log("custom host")\n')
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add memory-pgvector scaffolds workspace files', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-add-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({
    entrypointPath: 'entry.nrv',
    externals: ['user_message'],
  }, null, 2), 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'memory-pgvector', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.command, 'add')
    assert.equal(payload.capability, 'memory-pgvector')
    assert.equal(Array.isArray(payload.files), true)
    assert.equal(payload.composable?.providerLabel, 'memory-pgvector')
    assert.equal(payload.composable?.host, 'composable-reference-host')
    assert.equal(payload.composable?.autoAttach, true)

    const hostModulesSource = await readFile(path.join(workspaceRoot, 'host_modules', 'index.js'), 'utf8')
    const expectedImportPathRaw = path.relative(
      path.join(workspaceRoot, 'host_modules'),
      path.join(process.cwd(), 'src', 'host_modules', 'public', 'index.js'),
    ).replace(/\\/g, '/')
    const expectedImportPath = expectedImportPathRaw.startsWith('.')
      ? expectedImportPathRaw
      : `./${expectedImportPathRaw}`
    assert.equal(hostModulesSource.includes('Generated by nerve-compose add memory-pgvector'), true)
    assert.equal(hostModulesSource.includes('createMemoryProvider'), true)
    assert.equal(hostModulesSource.includes(`from '${expectedImportPath}'`), true)

    const memorySetupSource = await readFile(path.join(workspaceRoot, 'capabilities', 'memory', 'db-helpers', 'memory-setup.js'), 'utf8')
    assert.equal(memorySetupSource.includes('Generated by nerve-compose add memory-pgvector (memory-setup helper)'), true)
    assert.equal(memorySetupSource.includes('export async function initializeMemoryTable'), true)
    assert.equal(memorySetupSource.includes('CREATE TABLE IF NOT EXISTS memory'), true)

    const memoryHealthSource = await readFile(path.join(workspaceRoot, 'capabilities', 'memory', 'db-helpers', 'memory-health.js'), 'utf8')
    assert.equal(memoryHealthSource.includes('Generated by nerve-compose add memory-pgvector (memory-health helper)'), true)
    assert.equal(memoryHealthSource.includes('export async function testMemoryConnection'), true)
    assert.equal(memoryHealthSource.includes('SELECT 1 AS ok'), true)

    const envExample = await readFile(path.join(workspaceRoot, '.env.example'), 'utf8')
    assert.equal(envExample.includes('MEMORY_DB_URL='), true)
    assert.equal(envExample.includes('MEMORY_EMBEDDING_MODEL='), true)
    assert.equal(envExample.includes('MEMORY_EMBEDDING_API_KEY='), true)

    const env = await readFile(path.join(workspaceRoot, '.env'), 'utf8')
    assert.equal(env.includes('MEMORY_DB_URL=postgres://user:pass@localhost:5432/mock_memory'), true)
    assert.equal(env.includes('MEMORY_EMBEDDING_BASE_URL=http://127.0.0.1:11434'), true)
    assert.equal(env.includes('MEMORY_EMBEDDING_API_KEY='), true)

    const nextvRaw = await readFile(path.join(workspaceRoot, 'nextv.json'), 'utf8')
    const nextv = JSON.parse(nextvRaw)
    assert.deepEqual(nextv.requires?.memory, { required: true, provider: 'memory' })
    assert.deepEqual(nextv.modules?.memory, { provider: 'memory-pgvector', mode: 'embedded' })
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add memory-pgvector updates nerve.json when both config files exist', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-add-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nerve.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')
  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'memory-pgvector', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    const configEntry = payload.files.find((entry) => String(entry.path || '').endsWith('nerve.json'))
    assert.equal(Boolean(configEntry), true)

    const nerveRaw = await readFile(path.join(workspaceRoot, 'nerve.json'), 'utf8')
    const nerve = JSON.parse(nerveRaw)
    assert.deepEqual(nerve.requires?.memory, { required: true, provider: 'memory' })
    assert.deepEqual(nerve.modules?.memory, { provider: 'memory-pgvector', mode: 'embedded' })

    const nextvRaw = await readFile(path.join(workspaceRoot, 'nextv.json'), 'utf8')
    const nextv = JSON.parse(nextvRaw)
    assert.equal(nextv.requires?.memory, undefined)
    assert.equal(nextv.modules?.memory, undefined)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add transport ollama registers transport and env placeholders', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-transport-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nerve.json'), JSON.stringify({ entrypointPath: 'workflow.nrv' }, null, 2), 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'transport', 'ollama', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.capability, 'transport:ollama')

    const transports = JSON.parse(await readFile(path.join(workspaceRoot, 'transports.json'), 'utf8'))
    assert.deepEqual(transports.ollama, {
      provider: 'ollama',
      baseUrl: '${env:OLLAMA_BASE_URL}',
    })

    const envExample = await readFile(path.join(workspaceRoot, '.env.example'), 'utf8')
    assert.equal(envExample.includes('OLLAMA_BASE_URL='), true)

    const env = await readFile(path.join(workspaceRoot, '.env'), 'utf8')
    assert.equal(env.includes('OLLAMA_BASE_URL='), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add transport appends missing .env keys without overwriting existing values', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-transport-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nerve.json'), JSON.stringify({ entrypointPath: 'workflow.nrv' }, null, 2), 'utf8')
  await writeFile(path.join(workspaceRoot, '.env'), 'OLLAMA_BASE_URL=http://localhost:12345\n', 'utf8')

  try {
    const ollamaResult = await runProcess(['bin/nerve-compose.js', 'add', 'transport', 'ollama', workspaceRelativePath, '--json'])
    assert.equal(ollamaResult.code, 0)

    const openaiResult = await runProcess(['bin/nerve-compose.js', 'add', 'transport', 'openai', workspaceRelativePath, '--json'])
    assert.equal(openaiResult.code, 0)

    const env = await readFile(path.join(workspaceRoot, '.env'), 'utf8')
    assert.equal(env.includes('OLLAMA_BASE_URL=http://localhost:12345'), true)
    assert.equal(env.includes('OPENAI_BASE_URL=https://api.openai.com'), true)
    assert.equal(env.includes('OPENAI_API_KEY='), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add transport openai scaffolds env-backed config with only api key blank in .env', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-transport-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nerve.json'), JSON.stringify({ entrypointPath: 'workflow.nrv' }, null, 2), 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'transport', 'openai', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.capability, 'transport:openai')

    const transports = JSON.parse(await readFile(path.join(workspaceRoot, 'transports.json'), 'utf8'))
    assert.deepEqual(transports.openai, {
      provider: 'openai_compat',
      baseUrl: '${env:OPENAI_BASE_URL}',
      apiKey: '${env:OPENAI_API_KEY}',
    })

    const env = await readFile(path.join(workspaceRoot, '.env'), 'utf8')
    assert.equal(env.includes('OPENAI_BASE_URL=https://api.openai.com'), true)
    assert.equal(env.includes('OPENAI_API_KEY='), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add transport groq scaffolds env-backed config with only api key blank in .env', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-transport-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nerve.json'), JSON.stringify({ entrypointPath: 'workflow.nrv' }, null, 2), 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'transport', 'groq', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.capability, 'transport:groq')

    const transports = JSON.parse(await readFile(path.join(workspaceRoot, 'transports.json'), 'utf8'))
    assert.deepEqual(transports.groq, {
      provider: 'openai_compat',
      baseUrl: '${env:GROQ_BASE_URL}',
      apiKey: '${env:GROQ_API_KEY}',
    })

    const env = await readFile(path.join(workspaceRoot, '.env'), 'utf8')
    assert.equal(env.includes('GROQ_BASE_URL=https://api.groq.com/openai'), true)
    assert.equal(env.includes('GROQ_API_KEY='), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add transport gemini scaffolds env-backed config with only api key blank in .env', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-transport-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nerve.json'), JSON.stringify({ entrypointPath: 'workflow.nrv' }, null, 2), 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'transport', 'gemini', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.capability, 'transport:gemini')

    const transports = JSON.parse(await readFile(path.join(workspaceRoot, 'transports.json'), 'utf8'))
    assert.deepEqual(transports.gemini, {
      provider: 'openai_compat',
      baseUrl: '${env:GEMINI_BASE_URL}',
      apiKey: '${env:GEMINI_API_KEY}',
    })

    const env = await readFile(path.join(workspaceRoot, '.env'), 'utf8')
    assert.equal(env.includes('GEMINI_BASE_URL=https://generativelanguage.googleapis.com/v1beta/openai'), true)
    assert.equal(env.includes('GEMINI_API_KEY='), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add transport skips .env changes when workspace config is missing', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-transport-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'transport', 'ollama', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.files.some((entry) => String(entry.path || '').endsWith('.env')), false)
    assert.equal(existsSync(path.join(workspaceRoot, '.env')), false)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add transport is idempotent on rerun', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-transport-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nerve.json'), JSON.stringify({ entrypointPath: 'workflow.nrv' }, null, 2), 'utf8')

  try {
    const first = await runProcess(['bin/nerve-compose.js', 'add', 'transport', 'ollama', workspaceRelativePath, '--json'])
    assert.equal(first.code, 0)

    const second = await runProcess(['bin/nerve-compose.js', 'add', 'transport', 'ollama', workspaceRelativePath, '--json'])
    assert.equal(second.code, 0)

    const payload = JSON.parse(second.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.files.every((entry) => entry.action === 'unchanged' || entry.action === 'updated' || entry.action === 'skipped'), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add transport preserves existing inline transports map', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-transport-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nerve.json'), JSON.stringify({
    entrypointPath: 'workflow.nrv',
    transports: {
      custom: {
        provider: 'custom-provider',
      },
    },
  }, null, 2), 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'transport', 'ollama', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const nerve = JSON.parse(await readFile(path.join(workspaceRoot, 'nerve.json'), 'utf8'))
    assert.equal(Boolean(nerve.transports?.custom), true)
    assert.deepEqual(nerve.transports?.ollama, {
      provider: 'ollama',
      baseUrl: '${env:OLLAMA_BASE_URL}',
    })
    assert.equal(existsSync(path.join(workspaceRoot, 'transports.json')), false)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add model registers model with existing transport', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-model-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nerve.json'), JSON.stringify({
    entrypointPath: 'workflow.nrv',
    transports: {
      ollama: {
        provider: 'ollama',
        baseUrl: 'http://127.0.0.1:65535',
      },
    },
  }, null, 2), 'utf8')

  try {
    const result = await runProcess([
      'bin/nerve-compose.js',
      'add',
      'model',
      'llama3.2',
      '--transport',
      'ollama',
      workspaceRelativePath,
      '--json',
    ])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.capability, 'model:llama3.2')

    const models = JSON.parse(await readFile(path.join(workspaceRoot, 'models.json'), 'utf8'))
    assert.deepEqual(models['llama3.2'], {
      model: 'llama3.2',
      transport: 'ollama',
    })
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add model resolves unique ollama prefix to exact label', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-model-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')
  const mockServer = await startMockOllamaTagsServer(['llama3.2:latest'])

  await writeFile(path.join(workspaceRoot, 'nerve.json'), JSON.stringify({
    entrypointPath: 'workflow.nrv',
    transports: {
      ollama: {
        provider: 'ollama',
        baseUrl: mockServer.baseUrl,
      },
    },
  }, null, 2), 'utf8')

  try {
    const result = await runProcess([
      'bin/nerve-compose.js',
      'add',
      'model',
      'llama3.2',
      '--transport',
      'ollama',
      workspaceRelativePath,
      '--json',
    ])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.capability, 'model:llama3.2:latest')

    const modelEntry = payload.files.find((entry) => String(entry.message || '').includes('resolved model'))
    assert.equal(Boolean(modelEntry), true)

    const models = JSON.parse(await readFile(path.join(workspaceRoot, 'models.json'), 'utf8'))
    assert.deepEqual(models['llama3.2:latest'], {
      model: 'llama3.2:latest',
      transport: 'ollama',
    })
    assert.equal(models['llama3.2'], undefined)
  } finally {
    await mockServer.close()
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add model preserves existing inline models map', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-model-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nerve.json'), JSON.stringify({
    entrypointPath: 'workflow.nrv',
    transports: {
      ollama: {
        provider: 'ollama',
        baseUrl: 'http://127.0.0.1:65535',
      },
    },
    models: {
      existing: {
        model: 'existing',
        transport: 'ollama',
      },
    },
  }, null, 2), 'utf8')

  try {
    const result = await runProcess([
      'bin/nerve-compose.js',
      'add',
      'model',
      'llama3.2',
      '--transport',
      'ollama',
      workspaceRelativePath,
      '--json',
    ])
    assert.equal(result.code, 0)

    const nerve = JSON.parse(await readFile(path.join(workspaceRoot, 'nerve.json'), 'utf8'))
    assert.equal(Boolean(nerve.models?.existing), true)
    assert.deepEqual(nerve.models?.['llama3.2'], {
      model: 'llama3.2',
      transport: 'ollama',
    })
    assert.equal(existsSync(path.join(workspaceRoot, 'models.json')), false)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add model reads transport from transports.json', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-model-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nerve.json'), JSON.stringify({
    entrypointPath: 'workflow.nrv',
  }, null, 2), 'utf8')
  await writeFile(path.join(workspaceRoot, 'transports.json'), JSON.stringify({
    ollama: {
      provider: 'ollama',
      baseUrl: 'http://127.0.0.1:65535',
    },
  }, null, 2), 'utf8')

  try {
    const result = await runProcess([
      'bin/nerve-compose.js',
      'add',
      'model',
      'llama3.2',
      '--transport',
      'ollama',
      workspaceRelativePath,
      '--json',
    ])
    assert.equal(result.code, 0)

    const models = JSON.parse(await readFile(path.join(workspaceRoot, 'models.json'), 'utf8'))
    assert.deepEqual(models['llama3.2'], {
      model: 'llama3.2',
      transport: 'ollama',
    })
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add model fails when referenced transport is missing', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-model-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nerve.json'), JSON.stringify({ entrypointPath: 'workflow.nrv' }, null, 2), 'utf8')

  try {
    const result = await runProcess([
      'bin/nerve-compose.js',
      'add',
      'model',
      'llama3.2',
      '--transport',
      'ollama',
      workspaceRelativePath,
      '--json',
    ])
    assert.equal(result.code, 1)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, false)
    const skipped = payload.files.find((entry) => String(entry.message || '').includes('transport "ollama" not found'))
    assert.equal(Boolean(skipped), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add model requires --transport flag', async () => {
  const result = await runProcess(['bin/nerve-compose.js', 'add', 'model', 'llama3.2', '--json'])
  assert.equal(result.code, 2)
  assert.equal(result.stderr.includes('add model requires --transport <transportName>'), true)
})

test('nerve-compose add docs requires profile', async () => {
  const result = await runProcess(['bin/nerve-compose.js', 'add', 'docs', '--json'])
  assert.equal(result.code, 2)
  assert.equal(result.stderr.includes('add docs requires <profile>'), true)
})

test('nerve-compose add docs rejects invalid profile', async () => {
  const result = await runProcess(['bin/nerve-compose.js', 'add', 'docs', 'invalid', '--json'])
  assert.equal(result.code, 2)
  assert.equal(result.stderr.includes('add docs profile must be one of: minimal, ai'), true)
})

test('nerve-compose add docs minimal copies guide docs into docs/guide', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-docs-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'docs', 'minimal', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.capability, 'docs:minimal')

    const copiedGuidePath = path.join(workspaceRoot, 'docs', 'guide', '01-what-is-nerve.md')
    const copiedGuide = await readFile(copiedGuidePath, 'utf8')
    assert.equal(copiedGuide.includes('# What Is Nerveflow'), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add docs ai copies project-generation docs and rules file', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-docs-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'docs', 'ai', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.capability, 'docs:ai')

    const projectGuidePath = path.join(workspaceRoot, 'docs', 'project-generation', 'project-generator-guide.md')
    const projectGuide = await readFile(projectGuidePath, 'utf8')
    assert.equal(projectGuide.includes('# Project Generator Guide'), true)

    const rulesPath = path.join(workspaceRoot, 'NERVEFLOW_AGENT_RULES.md')
    const rules = await readFile(rulesPath, 'utf8')
    assert.equal(rules.includes('# Nerveflow Agent Rules'), true)
    assert.equal(rules.includes('The user explicitly enabled ecosystem feedback suggestions for this workspace.'), false)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add docs rerun is non-destructive for diverged files', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-docs-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  try {
    const first = await runProcess(['bin/nerve-compose.js', 'add', 'docs', 'minimal', workspaceRelativePath, '--json'])
    assert.equal(first.code, 0)

    const targetFilePath = path.join(workspaceRoot, 'docs', 'guide', '01-what-is-nerve.md')
    await writeFile(targetFilePath, '# user custom copy\n', 'utf8')

    const second = await runProcess(['bin/nerve-compose.js', 'add', 'docs', 'minimal', workspaceRelativePath, '--json'])
    assert.equal(second.code, 1)

    const payload = JSON.parse(second.stdout)
    assert.equal(payload.ok, false)
    const skippedEntry = payload.files.find(
      (entry) => String(entry.path || '').replace(/\\/g, '/').endsWith('docs/guide/01-what-is-nerve.md')
    )
    assert.equal(Boolean(skippedEntry), true)
    assert.equal(skippedEntry.action, 'skipped_manual_merge')

    const preserved = await readFile(targetFilePath, 'utf8')
    assert.equal(preserved, '# user custom copy\n')
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add docs ai --with-agent-instructions scaffolds instruction files', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-docs-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  try {
    const result = await runProcess([
      'bin/nerve-compose.js',
      'add',
      'docs',
      'ai',
      '--with-agent-instructions',
      workspaceRelativePath,
      '--json',
    ])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)

    const copilotPath = path.join(workspaceRoot, '.github', 'copilot-instructions.md')
    const claudePath = path.join(workspaceRoot, 'CLAUDE.md')
    const agentsPath = path.join(workspaceRoot, 'AGENTS.md')

    const copilot = await readFile(copilotPath, 'utf8')
    const claude = await readFile(claudePath, 'utf8')
    const agents = await readFile(agentsPath, 'utf8')

    assert.equal(copilot.includes('BEGIN NERVEFLOW AI INSTRUCTIONS'), true)
    assert.equal(claude.includes('BEGIN NERVEFLOW AI INSTRUCTIONS'), true)
    assert.equal(agents.includes('BEGIN NERVEFLOW AI INSTRUCTIONS'), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add docs ai --instructions-only --with-agent-instructions skips docs copy', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-docs-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  try {
    const result = await runProcess([
      'bin/nerve-compose.js',
      'add',
      'docs',
      'ai',
      '--instructions-only',
      '--with-agent-instructions',
      workspaceRelativePath,
      '--json',
    ])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)

    assert.equal(existsSync(path.join(workspaceRoot, 'docs', 'project-generation')), false)
    assert.equal(existsSync(path.join(workspaceRoot, '.github', 'copilot-instructions.md')), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add docs ai --no-prompts does not scaffold instruction files by default', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-docs-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  try {
    const result = await runProcess([
      'bin/nerve-compose.js',
      'add',
      'docs',
      'ai',
      '--no-prompts',
      workspaceRelativePath,
      '--json',
    ])
    assert.equal(result.code, 0)

    assert.equal(existsSync(path.join(workspaceRoot, '.github', 'copilot-instructions.md')), false)
    assert.equal(existsSync(path.join(workspaceRoot, 'CLAUDE.md')), false)
    assert.equal(existsSync(path.join(workspaceRoot, 'AGENTS.md')), false)

    const rules = await readFile(path.join(workspaceRoot, 'NERVEFLOW_AGENT_RULES.md'), 'utf8')
    assert.equal(rules.includes('The user explicitly enabled ecosystem feedback suggestions for this workspace.'), false)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add docs ai appends managed block to existing CLAUDE.md', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-docs-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')
  const claudePath = path.join(workspaceRoot, 'CLAUDE.md')

  await writeFile(claudePath, '# custom notes\nkeep this\n', 'utf8')

  try {
    const first = await runProcess([
      'bin/nerve-compose.js',
      'add',
      'docs',
      'ai',
      '--with-agent-instructions',
      workspaceRelativePath,
      '--json',
    ])
    assert.equal(first.code, 0)

    const afterFirst = await readFile(claudePath, 'utf8')
    assert.equal(afterFirst.includes('# custom notes'), true)
    assert.equal(afterFirst.includes('BEGIN NERVEFLOW AI INSTRUCTIONS'), true)

    const second = await runProcess([
      'bin/nerve-compose.js',
      'add',
      'docs',
      'ai',
      '--with-agent-instructions',
      workspaceRelativePath,
      '--json',
    ])
    assert.equal(second.code, 0)

    const afterSecond = await readFile(claudePath, 'utf8')
    const markerMatches = afterSecond.match(/BEGIN NERVEFLOW AI INSTRUCTIONS/g) || []
    assert.equal(markerMatches.length, 1)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add docs ai-only flags are rejected for non-ai profile', async () => {
  const result = await runProcess(['bin/nerve-compose.js', 'add', 'docs', 'minimal', '--with-agent-instructions', '--json'])
  assert.equal(result.code, 2)
  assert.equal(
    result.stderr.includes('--with-agent-instructions, --no-prompts, and --instructions-only are only valid for add docs ai'),
    true,
  )
})

test('nerve-compose add memory-pgvector is idempotent on rerun', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-add-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')

  try {
    const first = await runProcess(['bin/nerve-compose.js', 'add', 'memory-pgvector', workspaceRelativePath, '--json'])
    assert.equal(first.code, 0)

    const second = await runProcess(['bin/nerve-compose.js', 'add', 'memory-pgvector', workspaceRelativePath, '--json'])
    assert.equal(second.code, 0)

    const payload = JSON.parse(second.stdout)
    const actions = payload.files.map((entry) => entry.action)
    assert.equal(actions.every((action) => action === 'unchanged' || action === 'updated' || action === 'skipped'), true)

    const envExample = await readFile(path.join(workspaceRoot, '.env.example'), 'utf8')
    const dbUrlMatches = envExample.match(/MEMORY_DB_URL=/g) || []
    assert.equal(dbUrlMatches.length, 1)

    const env = await readFile(path.join(workspaceRoot, '.env'), 'utf8')
    const runtimeDbUrlMatches = env.match(/MEMORY_DB_URL=/g) || []
    assert.equal(runtimeDbUrlMatches.length, 1)
    const runtimeEmbeddingApiKeyMatches = env.match(/MEMORY_EMBEDDING_API_KEY=/g) || []
    assert.equal(runtimeEmbeddingApiKeyMatches.length, 1)

    const hostModulesSource = await readFile(path.join(workspaceRoot, 'host_modules', 'index.js'), 'utf8')
    const createMemoryProviderMatches = hostModulesSource.match(/createMemoryProvider/g) || []
    assert.equal(createMemoryProviderMatches.length, 2)

    const memorySetupSource = await readFile(path.join(workspaceRoot, 'capabilities', 'memory', 'db-helpers', 'memory-setup.js'), 'utf8')
    const setupMarkerMatches = memorySetupSource.match(/Generated by nerve-compose add memory-pgvector \(memory-setup helper\)/g) || []
    assert.equal(setupMarkerMatches.length, 1)

    const memoryHealthSource = await readFile(path.join(workspaceRoot, 'capabilities', 'memory', 'db-helpers', 'memory-health.js'), 'utf8')
    const healthMarkerMatches = memoryHealthSource.match(/Generated by nerve-compose add memory-pgvector \(memory-health helper\)/g) || []
    assert.equal(healthMarkerMatches.length, 1)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add memory-pgvector skips manual merge for non-generated db helper files', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-add-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')
  await mkdir(path.join(workspaceRoot, 'capabilities', 'memory', 'db-helpers'), { recursive: true })
  await writeFile(path.join(workspaceRoot, 'capabilities', 'memory', 'db-helpers', 'memory-setup.js'), 'export const manual = true\n', 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'memory-pgvector', workspaceRelativePath, '--json'])
    assert.equal(result.code, 1)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, false)
    const setupEntry = payload.files.find((entry) => String(entry.path || '').replace(/\\/g, '/').endsWith('capabilities/memory/db-helpers/memory-setup.js'))
    assert.equal(Boolean(setupEntry), true)
    assert.equal(setupEntry.action, 'skipped_manual_merge')

    const preserved = await readFile(path.join(workspaceRoot, 'capabilities', 'memory', 'db-helpers', 'memory-setup.js'), 'utf8')
    assert.equal(preserved, 'export const manual = true\n')
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add memory-pgvector appends missing .env keys without overwriting existing values', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-add-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')
  await writeFile(path.join(workspaceRoot, '.env'), 'MEMORY_DB_URL=postgres://localhost:5432/custom_memory\n', 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'memory-pgvector', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const env = await readFile(path.join(workspaceRoot, '.env'), 'utf8')
    assert.equal(env.includes('MEMORY_DB_URL=postgres://localhost:5432/custom_memory'), true)
    assert.equal(env.includes('MEMORY_EMBEDDING_BASE_URL=http://127.0.0.1:11434'), true)
    assert.equal(env.includes('MEMORY_EMBEDDING_API_KEY='), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add memory-pgvector --blank scaffolds blank MEMORY_DB_URL in .env', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-add-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'memory-pgvector', workspaceRelativePath, '--blank', '--json'])
    assert.equal(result.code, 0)

    const env = await readFile(path.join(workspaceRoot, '.env'), 'utf8')
    assert.equal(env.includes('MEMORY_DB_URL='), true)
    assert.equal(env.includes('MEMORY_DB_URL=postgres://'), false)
    assert.equal(env.includes('MEMORY_EMBEDDING_API_KEY='), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add transport rejects --blank flag', async () => {
  const result = await runProcess(['bin/nerve-compose.js', 'add', 'transport', 'ollama', '--blank', '--json'])
  assert.equal(result.code, 2)
  assert.equal(result.stderr.includes('--blank is only valid for add memory-pgvector'), true)
})

test('nerve-compose add memory-pgvector becomes visible in modules after env is provided', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), 'workspaces-local', '.tmp-compose-add-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')

  try {
    const addResult = await runProcess(['bin/nerve-compose.js', 'add', 'memory-pgvector', workspaceRelativePath, '--json'])
    assert.equal(addResult.code, 0)

    await writeFile(path.join(workspaceRoot, '.env'), 'MEMORY_DB_URL=postgres://example/test\n', 'utf8')

    const modulesResult = await runProcess(['bin/nerve-compose.js', 'modules', workspaceRelativePath, '--json'])
    assert.equal(modulesResult.code, 0)

    const payload = JSON.parse(modulesResult.stdout)
    const workspaceSource = payload.sources.find((source) => source?.name === 'workspace')
    assert.equal(Boolean(workspaceSource), true)
    assert.equal(Number(workspaceSource.counts?.toolProviders) > 0, true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add memory-spa scaffolds files when memory-pgvector binding exists', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-memory-spa-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({
    entrypointPath: 'entry.nrv',
    requires: {
      memory: {
        required: true,
        provider: 'memory',
      },
    },
    modules: {
      memory: {
        provider: 'memory-pgvector',
        mode: 'embedded',
      },
    },
  }, null, 2), 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'memory-spa', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.capability, 'memory-spa')
    assert.equal(payload.composable?.providerLabel, 'memory-spa')

    assert.equal(existsSync(path.join(workspaceRoot, 'memory-spa', 'README.md')), true)
    assert.equal(existsSync(path.join(workspaceRoot, 'memory-spa', 'public', 'index.html')), true)
    assert.equal(existsSync(path.join(workspaceRoot, 'memory-spa', 'server.mjs')), true)

    const serverSource = await readFile(path.join(workspaceRoot, 'memory-spa', 'server.mjs'), 'utf8')
    const expectedImportPathRaw = path.relative(
      path.join(workspaceRoot, 'memory-spa'),
      path.join(process.cwd(), 'src', 'host_modules', 'public', 'index.js'),
    ).replace(/\\/g, '/')
    const expectedImportPath = expectedImportPathRaw.startsWith('.')
      ? expectedImportPathRaw
      : `./${expectedImportPathRaw}`

    assert.equal(serverSource.includes('Generated by nerve-compose add memory-spa'), true)
    assert.equal(serverSource.includes(`from '${expectedImportPath}'`), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add memory-spa requires memory-pgvector capability binding first', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-memory-spa-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'memory-spa', workspaceRelativePath, '--json'])
    assert.equal(result.code, 1)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, false)
    const skippedEntry = payload.files.find((entry) => String(entry.path || '').replace(/\\/g, '/').endsWith('nextv.json'))
    assert.equal(Boolean(skippedEntry), true)
    assert.equal(skippedEntry.action, 'skipped')
    assert.equal(String(skippedEntry.message || '').includes('add memory-pgvector first'), true)
    assert.equal(existsSync(path.join(workspaceRoot, 'memory-spa')), false)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add memory-spa is idempotent on rerun', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-memory-spa-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({
    entrypointPath: 'entry.nrv',
    requires: {
      memory: {
        required: true,
        provider: 'memory',
      },
    },
    modules: {
      memory: {
        provider: 'memory-pgvector',
        mode: 'embedded',
      },
    },
  }, null, 2), 'utf8')

  try {
    const first = await runProcess(['bin/nerve-compose.js', 'add', 'memory-spa', workspaceRelativePath, '--json'])
    assert.equal(first.code, 0)

    const second = await runProcess(['bin/nerve-compose.js', 'add', 'memory-spa', workspaceRelativePath, '--json'])
    assert.equal(second.code, 0)

    const payload = JSON.parse(second.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.files.every((entry) => entry.action === 'unchanged' || entry.action === 'updated'), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add memory-spa skips manual merge for custom memory-spa/server.mjs', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-memory-spa-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({
    entrypointPath: 'entry.nrv',
    requires: {
      memory: {
        required: true,
        provider: 'memory',
      },
    },
    modules: {
      memory: {
        provider: 'memory-pgvector',
        mode: 'embedded',
      },
    },
  }, null, 2), 'utf8')

  await mkdir(path.join(workspaceRoot, 'memory-spa'), { recursive: true })
  await writeFile(path.join(workspaceRoot, 'memory-spa', 'server.mjs'), 'console.log("custom memory spa server")\n', 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'memory-spa', workspaceRelativePath, '--json'])
    assert.equal(result.code, 1)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, false)
    const serverEntry = payload.files.find((entry) => String(entry.path || '').replace(/\\/g, '/').endsWith('memory-spa/server.mjs'))
    assert.equal(Boolean(serverEntry), true)
    assert.equal(serverEntry.action, 'skipped_manual_merge')

    const serverSource = await readFile(path.join(workspaceRoot, 'memory-spa', 'server.mjs'), 'utf8')
    assert.equal(serverSource, 'console.log("custom memory spa server")\n')
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add speech scaffolds env, nextv config, and speech surface', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-speech-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'speech', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.capability, 'speech')
    assert.equal(Array.isArray(payload.files), true)
    assert.equal(payload.composable?.providerLabel, 'speech-surface')
    assert.equal(payload.composable?.host, 'composable-reference-host')
    assert.equal(payload.composable?.autoAttach, true)

    const hostModulesSource = await readFile(path.join(workspaceRoot, 'host_modules', 'index.js'), 'utf8')
    assert.equal(hostModulesSource.includes('Generated by nerve-compose add speech'), true)
    assert.equal(hostModulesSource.includes('createWhisperIngressConnector'), true)
    assert.equal(hostModulesSource.includes('createPiperEffectRealizer'), true)

    const rootEnvExamplePath = path.join(workspaceRoot, '.env.example')
    if (existsSync(rootEnvExamplePath)) {
      const envExample = await readFile(rootEnvExamplePath, 'utf8')
      assert.equal(envExample.includes('WHISPER_RUN_PATH='), false)
      assert.equal(envExample.includes('PIPER_RUN_PATH='), false)
      assert.equal(envExample.includes('VOICE_TRANSPORT_MODE='), false)
    }

    const nextvRaw = await readFile(path.join(workspaceRoot, 'nextv.json'), 'utf8')
    const nextv = JSON.parse(nextvRaw)
    assert.deepEqual(nextv.requires?.speech, { required: true, provider: 'speech' })
    assert.deepEqual(nextv.modules?.speech, { provider: 'speech-surface', mode: 'embedded' })

    const speechSurfaceServer = await readFile(path.join(workspaceRoot, 'voice-spa', 'server.js'), 'utf8')
    assert.equal(speechSurfaceServer.includes('/api/voice-command'), true)
    assert.equal(speechSurfaceServer.includes("'../capabilities/speech/server_lib.mjs'"), true)

    const speechSurfaceEnvExample = await readFile(path.join(workspaceRoot, 'voice-spa', '.env.example'), 'utf8')
    assert.equal(speechSurfaceEnvExample.includes('WHISPER_RUN_PATH='), true)
    assert.equal(speechSurfaceEnvExample.includes('PIPER_RUN_PATH='), true)
    assert.equal(speechSurfaceEnvExample.includes('VOICE_TRANSPORT_MODE='), true)

    const speechSurfaceLib = await readFile(path.join(workspaceRoot, 'capabilities', 'speech', 'server_lib.mjs'), 'utf8')
    assert.equal(speechSurfaceLib.includes('voice-spa/.env'), true)

    const speechUiPackage = await readFile(path.join(workspaceRoot, 'voice-spa', 'package.json'), 'utf8')
    assert.equal(JSON.parse(speechUiPackage).type, 'module')
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add speech is idempotent on rerun', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-speech-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')

  try {
    const first = await runProcess(['bin/nerve-compose.js', 'add', 'speech', workspaceRelativePath, '--json'])
    assert.equal(first.code, 0)

    const second = await runProcess(['bin/nerve-compose.js', 'add', 'speech', workspaceRelativePath, '--json'])
    assert.equal(second.code, 0)

    const payload = JSON.parse(second.stdout)
    const actions = payload.files.map((entry) => entry.action)
    assert.equal(actions.includes('created'), false)
    assert.equal(actions.every((action) => action === 'unchanged' || action === 'updated' || action === 'skipped'), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add semantic-surface scaffolds host modules, config, and surface files', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-semantic-surface-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'semantic-surface', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.capability, 'semantic-surface')
    assert.equal(payload.composable?.providerLabel, 'semantic-surface')
    assert.equal(payload.composable?.host, 'composable-reference-host')
    assert.equal(payload.composable?.autoAttach, true)

    const hostModulesSource = await readFile(path.join(workspaceRoot, 'host_modules', 'index.js'), 'utf8')
    assert.equal(hostModulesSource.includes('Generated by nerve-compose add semantic-surface'), true)
    assert.equal(hostModulesSource.includes('createSemanticSurfaceIngressConnector'), true)
    assert.equal(hostModulesSource.includes('createSemanticSurfaceEffectRealizer'), true)

    const nextvRaw = await readFile(path.join(workspaceRoot, 'nextv.json'), 'utf8')
    const nextv = JSON.parse(nextvRaw)
    assert.deepEqual(nextv.requires?.['semantic-surface'], { required: true, provider: 'semantic-surface' })
    assert.deepEqual(nextv.modules?.['semantic-surface'], { provider: 'semantic-surface', mode: 'embedded' })
    assert.equal(Array.isArray(nextv.externals), true)
    assert.equal(nextv.externals.includes('semantic_surface_event'), true)
    assert.deepEqual(nextv.effects?.semantic_surface, { kind: 'surface', format: 'json' })

    const surfaceServer = await readFile(path.join(workspaceRoot, 'semantic-surface', 'server.js'), 'utf8')
    assert.equal(surfaceServer.includes("'../capabilities/semantic-surface/server.mjs'"), true)
    assert.equal(surfaceServer.includes('/api/interactions'), true)

    const capabilityServer = await readFile(path.join(workspaceRoot, 'capabilities', 'semantic-surface', 'server.mjs'), 'utf8')
    assert.equal(capabilityServer.includes('createSemanticSurfaceIngressConnector'), true)
    assert.equal(capabilityServer.includes('getSemanticSurfaceSnapshot'), true)

    const surfaceApp = await readFile(path.join(workspaceRoot, 'semantic-surface', 'public', 'app.js'), 'utf8')
    assert.equal(surfaceApp.includes("fetch('./api/interactions'"), true)

    const surfacePackage = await readFile(path.join(workspaceRoot, 'semantic-surface', 'package.json'), 'utf8')
    assert.equal(JSON.parse(surfacePackage).type, 'module')
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add semantic-surface updates nerve.json when both config files exist', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-semantic-surface-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nerve.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')
  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'semantic-surface', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    const configEntry = payload.files.find((entry) => String(entry.path || '').endsWith('nerve.json'))
    assert.equal(Boolean(configEntry), true)

    const nerveRaw = await readFile(path.join(workspaceRoot, 'nerve.json'), 'utf8')
    const nerve = JSON.parse(nerveRaw)
    assert.deepEqual(nerve.requires?.['semantic-surface'], { required: true, provider: 'semantic-surface' })
    assert.deepEqual(nerve.modules?.['semantic-surface'], { provider: 'semantic-surface', mode: 'embedded' })
    assert.equal(Array.isArray(nerve.externals), true)
    assert.equal(nerve.externals.includes('semantic_surface_event'), true)
    assert.deepEqual(nerve.effects?.semantic_surface, { kind: 'surface', format: 'json' })

    const nextvRaw = await readFile(path.join(workspaceRoot, 'nextv.json'), 'utf8')
    const nextv = JSON.parse(nextvRaw)
    assert.equal(nextv.requires?.['semantic-surface'], undefined)
    assert.equal(nextv.modules?.['semantic-surface'], undefined)
    assert.equal(nextv.effects?.semantic_surface, undefined)
    assert.equal(Array.isArray(nextv.externals), false)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add semantic-surface merges config without clobbering existing externals/effects', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-semantic-surface-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({
    entrypointPath: 'entry.nrv',
    externals: ['user_message'],
    effects: {
      custom_channel: {
        kind: 'surface',
        format: 'json',
      },
      semantic_surface: {
        format: 'interaction',
      },
    },
  }, null, 2), 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'semantic-surface', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)

    const nextvRaw = await readFile(path.join(workspaceRoot, 'nextv.json'), 'utf8')
    const nextv = JSON.parse(nextvRaw)
    assert.equal(nextv.externals.includes('user_message'), true)
    assert.equal(nextv.externals.includes('semantic_surface_event'), true)
    assert.deepEqual(nextv.effects?.custom_channel, { kind: 'surface', format: 'json' })
    assert.deepEqual(nextv.effects?.semantic_surface, { kind: 'surface', format: 'interaction' })
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add semantic-surface is idempotent on rerun', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-semantic-surface-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')

  try {
    const first = await runProcess(['bin/nerve-compose.js', 'add', 'semantic-surface', workspaceRelativePath, '--json'])
    assert.equal(first.code, 0)

    const second = await runProcess(['bin/nerve-compose.js', 'add', 'semantic-surface', workspaceRelativePath, '--json'])
    assert.equal(second.code, 0)

    const payload = JSON.parse(second.stdout)
    const actions = payload.files.map((entry) => entry.action)
    assert.equal(actions.includes('created'), false)
    assert.equal(actions.every((action) => action === 'unchanged' || action === 'updated' || action === 'skipped'), true)

    const nextvRaw = await readFile(path.join(workspaceRoot, 'nextv.json'), 'utf8')
    const nextv = JSON.parse(nextvRaw)
    assert.equal(Array.isArray(nextv.externals), true)
    assert.equal(nextv.externals.filter((value) => value === 'semantic_surface_event').length, 1)
    assert.deepEqual(nextv.effects?.semantic_surface, { kind: 'surface', format: 'json' })
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add mcp scaffolds local server and external module config by default', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-mcp-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'mcp', workspaceRelativePath, '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.command, 'add')
    assert.equal(payload.capability, 'mcp')
    assert.equal(payload.composable?.providerLabel, 'mcp')
    assert.equal(payload.composable?.host, 'composable-reference-host')
    assert.equal(payload.composable?.autoAttach, true)

    const serverSource = await readFile(path.join(workspaceRoot, 'capabilities', 'mcp', 'servers', 'local-mcp.mjs'), 'utf8')
    assert.equal(serverSource.includes('Generated by nerve-compose add mcp'), true)
    assert.equal(serverSource.includes("registerTool('get_time'"), true)

    const mcpConfigRaw = await readFile(path.join(workspaceRoot, 'capabilities', 'mcp', 'mcp.json'), 'utf8')
    const mcpConfig = JSON.parse(mcpConfigRaw)
    assert.equal(Array.isArray(mcpConfig.servers), true)
    assert.deepEqual(mcpConfig.servers?.[0], {
      name: 'local-mcp',
      transport: 'stdio',
      config: {
        command: 'node',
        args: ['./capabilities/mcp/servers/local-mcp.mjs'],
      },
    })

    const nextvRaw = await readFile(path.join(workspaceRoot, 'nextv.json'), 'utf8')
    const nextv = JSON.parse(nextvRaw)
    assert.deepEqual(nextv.requires?.mcp, { required: true, provider: 'mcp' })
    assert.equal(nextv.modules?.mcp?.provider, 'mcp')
    assert.equal(nextv.modules?.mcp?.mode, 'embedded')
    assert.equal(nextv.modules?.mcp?.detectToolConflicts, true)
    assert.equal(nextv.modules?.mcp?.configPath, './capabilities/mcp/mcp.json')
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add mcp --inline keeps inline module config', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-mcp-inline-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')

  try {
    const result = await runProcess(['bin/nerve-compose.js', 'add', 'mcp', workspaceRelativePath, '--inline', '--json'])
    assert.equal(result.code, 0)

    const payload = JSON.parse(result.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.capability, 'mcp')

    await assert.rejects(
      () => readFile(path.join(workspaceRoot, 'capabilities', 'mcp', 'mcp.json'), 'utf8'),
      /ENOENT/,
    )

    const nextvRaw = await readFile(path.join(workspaceRoot, 'nextv.json'), 'utf8')
    const nextv = JSON.parse(nextvRaw)
    assert.deepEqual(nextv.requires?.mcp, { required: true, provider: 'mcp' })
    assert.equal(nextv.modules?.mcp?.provider, 'mcp')
    assert.equal(nextv.modules?.mcp?.detectToolConflicts, true)
    assert.equal(Array.isArray(nextv.modules?.mcp?.servers), true)
    assert.deepEqual(nextv.modules?.mcp?.servers?.[0], {
      name: 'local-mcp',
      transport: 'stdio',
      config: {
        command: 'node',
        args: ['./capabilities/mcp/servers/local-mcp.mjs'],
      },
    })
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})

test('nerve-compose add mcp is idempotent on rerun', async () => {
  const workspaceRoot = await mkdtemp(path.join(process.cwd(), '.tmp-compose-mcp-'))
  const workspaceRelativePath = path.relative(process.cwd(), workspaceRoot).replace(/\\/g, '/')

  await writeFile(path.join(workspaceRoot, 'nextv.json'), JSON.stringify({ entrypointPath: 'entry.nrv' }, null, 2), 'utf8')

  try {
    const first = await runProcess(['bin/nerve-compose.js', 'add', 'mcp', workspaceRelativePath, '--json'])
    assert.equal(first.code, 0)

    const second = await runProcess(['bin/nerve-compose.js', 'add', 'mcp', workspaceRelativePath, '--json'])
    assert.equal(second.code, 0)

    const payload = JSON.parse(second.stdout)
    assert.equal(payload.ok, true)
    assert.equal(payload.capability, 'mcp')
    const actions = payload.files.map((entry) => entry.action)
    assert.equal(actions.every((action) => action === 'unchanged' || action === 'updated' || action === 'skipped'), true)
  } finally {
    await rm(workspaceRoot, { recursive: true, force: true })
  }
})
