import { createServer } from 'node:http'
import { createReadStream, existsSync, readFileSync, statSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

// Generated by nerve-compose add memory-spa
import { createMemoryProvider } from '../../src/host_modules/public/index.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const PUBLIC_DIR = path.join(__dirname, 'public')
const PORT = Number(process.env.PORT ?? 4320)

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.ico': 'image/x-icon',
}

function stripMatchingQuotes(valueRaw) {
  const value = String(valueRaw ?? '')
  if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
    return value.slice(1, -1)
  }
  return value
}

function findWorkspaceDir() {
  const explicit = String(process.env.WORKSPACE_DIR ?? '').trim()
  if (explicit) return path.resolve(process.cwd(), explicit)

  let current = path.resolve(__dirname, '..')
  const root = path.parse(current).root
  for (let i = 0; i < 8; i += 1) {
    const hasWorkspaceSignal = existsSync(path.join(current, 'nerve.json'))
      || existsSync(path.join(current, 'nextv.json'))
      || existsSync(path.join(current, '.env'))
      || existsSync(path.join(current, 'package.json'))
    if (hasWorkspaceSignal) {
      return current
    }
    if (current === root) break
    current = path.dirname(current)
  }

  return path.resolve(__dirname, '..')
}

function loadWorkspaceEnv(workspaceDir) {
  const envPath = path.join(workspaceDir, '.env')
  if (!existsSync(envPath)) {
    return { loaded: false, envPath, applied: 0 }
  }

  const content = readFileSync(envPath, 'utf8')
  let applied = 0

  for (const rawLine of content.split(/\r?\n/)) {
    const line = String(rawLine ?? '').trim()
    if (!line || line.startsWith('#')) continue

    const cleaned = line.startsWith('export ') ? line.slice(7).trim() : line
    const eqIndex = cleaned.indexOf('=')
    if (eqIndex <= 0) continue

    const key = cleaned.slice(0, eqIndex).trim()
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue
    if (Object.prototype.hasOwnProperty.call(process.env, key)) continue

    process.env[key] = stripMatchingQuotes(cleaned.slice(eqIndex + 1).trim())
    applied += 1
  }

  return { loaded: true, envPath, applied }
}

function readJsonBody(req) {
  return new Promise((resolve, reject) => {
    let body = ''
    req.on('data', (chunk) => {
      body += String(chunk)
      if (body.length > 1024 * 1024) {
        reject(new Error('request body too large'))
      }
    })
    req.on('end', () => {
      if (!body.trim()) {
        resolve({})
        return
      }
      try {
        resolve(JSON.parse(body))
      } catch {
        reject(new Error('invalid JSON body'))
      }
    })
    req.on('error', reject)
  })
}

function writeJson(res, statusCode, payload) {
  res.writeHead(statusCode, { 'Content-Type': 'application/json; charset=utf-8' })
  res.end(JSON.stringify(payload))
}

function resolveSafeStaticPath(urlPath) {
  const normalizedPath = String(urlPath ?? '/').split('?')[0]
  const requestedPath = normalizedPath === '/' ? '/index.html' : normalizedPath
  const absolutePath = path.resolve(path.join(PUBLIC_DIR, requestedPath))
  if (!absolutePath.startsWith(PUBLIC_DIR)) {
    return null
  }
  return absolutePath
}

function createMemoryTools() {
  const provider = createMemoryProvider({
    pgUrl: process.env.MEMORY_DB_URL,
    embeddingModel: process.env.MEMORY_EMBEDDING_MODEL || 'nomic-embed-text:latest',
    embeddingBaseUrl: process.env.MEMORY_EMBEDDING_BASE_URL || 'http://127.0.0.1:11434',
    embeddingApiKey: process.env.MEMORY_EMBEDDING_API_KEY || '',
    embeddingDimensions: Number(process.env.MEMORY_EMBEDDING_DIMENSIONS ?? 768),
    poolMin: Number(process.env.MEMORY_POOL_MIN ?? 2),
    poolMax: Number(process.env.MEMORY_POOL_MAX ?? 10),
  })

  return {
    store: (input) => provider.memory_store({ named: input }),
    recall: (input) => provider.memory_retrieve({ named: input }),
    update: (input) => provider.memory_update({ named: input }),
    remove: (input) => provider.memory_delete({ named: input }),
  }
}

const workspaceDir = findWorkspaceDir()
const envLoad = loadWorkspaceEnv(workspaceDir)
const memory = createMemoryTools()

const server = createServer(async (req, res) => {
  try {
    if (req.method === 'GET' && req.url === '/health') {
      writeJson(res, 200, { ok: true, workspaceDir })
      return
    }

    if (req.method === 'POST' && req.url === '/api/memory/store') {
      const body = await readJsonBody(req)
      const result = await memory.store({
        text: body.text,
        metadata: body.metadata,
      })
      writeJson(res, 200, result)
      return
    }

    if (req.method === 'POST' && req.url === '/api/memory/recall') {
      const body = await readJsonBody(req)
      const result = await memory.recall({
        query_text: body.query_text,
        limit: body.limit,
        filter_metadata: body.filter_metadata,
      })
      writeJson(res, 200, result)
      return
    }

    if (req.method === 'POST' && req.url === '/api/memory/update') {
      const body = await readJsonBody(req)
      const result = await memory.update({
        id: body.id,
        text: body.text,
        metadata: body.metadata,
      })
      writeJson(res, 200, result)
      return
    }

    if (req.method === 'POST' && req.url === '/api/memory/delete') {
      const body = await readJsonBody(req)
      const result = await memory.remove({
        id: body.id,
      })
      writeJson(res, 200, result)
      return
    }

    if (req.method === 'GET') {
      const staticPath = resolveSafeStaticPath(req.url)
      if (!staticPath || !existsSync(staticPath) || statSync(staticPath).isDirectory()) {
        res.writeHead(404)
        res.end('Not found')
        return
      }

      const contentType = MIME[path.extname(staticPath)] || 'application/octet-stream'
      res.writeHead(200, { 'Content-Type': contentType })
      createReadStream(staticPath).pipe(res)
      return
    }

    res.writeHead(405)
    res.end('Method not allowed')
  } catch (error) {
    writeJson(res, 400, {
      ok: false,
      error: String(error?.message ?? error),
    })
  }
})

server.listen(PORT, '127.0.0.1', () => {
  const suffix = envLoad.loaded
    ? ` loaded ${envLoad.applied} env var(s) from ${envLoad.envPath}`
    : ' no .env file found'
  console.log(`Memory SPA listening at http://127.0.0.1:${PORT}`)
  console.log(`Workspace: ${workspaceDir}`)
  console.log(`Env:${suffix}`)
})
