// Generated by nerve-compose add memory-pgvector
import { createMemoryProvider } from '../../../src/host_modules/public/index.js'

export function createProviders() {
  return [
    createMemoryProvider({
      pgUrl: process.env.MEMORY_DB_URL,
      embeddingModel: process.env.MEMORY_EMBEDDING_MODEL || 'nomic-embed-text:latest',
      embeddingBaseUrl: process.env.MEMORY_EMBEDDING_BASE_URL || 'http://127.0.0.1:11434',
      embeddingDimensions: Number(process.env.MEMORY_EMBEDDING_DIMENSIONS ?? 768),
      poolMin: Number(process.env.MEMORY_POOL_MIN ?? 2),
      poolMax: Number(process.env.MEMORY_POOL_MAX ?? 10),
    }),
  ]
}
